### ISSUE TITLE
SP-Cabreúva

### ISSUE THREAD

**Issue by IgorEliezer** [AddressForAll/WS#14]
**((RASCUNHO))**

Parte do projeto [VIVO - Cidades para teste ](https://github.com/AddressForAll/WS/projects/5).

---

Parte OSM:
- [ ] Contagem de objetos.

Parte A4A:
- [ ] Levantar o que temos.
- [ ] Levantar o que precisa ser feito.

**Comment by ppKrauss** [comment]
Oops, **local ERRADO**. Por favor deletar tudo daqui e copiar/colar para
https://github.com/AddressForAll/digital-preservartion-BR/issues
