### ISSUE TITLE
Produzir makefile de cada pacote de dados 

### ISSUE THREAD

**Issue by ppKrauss** [AddressForAll/WS#16]
Ja se encontra em operacao o [_workflow_ da Eclusa](http://api-test.addressforall.org/v1.htm/nav_eclusa/), que garante a integridade e custodia segura dos dados doados ou resgatados pelo Instituto.  Como a mesma pessoa que efetua o FTP nao precisa ser a pessoa que constroe os scripts de ingestao, podemos convencionar o seguinte, com as seguintes responsabilidades:

1. Igor fecha o pactote e garante sua homologacao no http://api-test.addressforall.org/v1.htm/nav_core/origin

2. Carlos, a cada pacote (visivel no ls /home/igor/ ) avaliar com Igor o que fazer para gerar dados no PostGIS, e traduzir em script Linux, postando o mesmo como `makefile` na pasta do pacote. Cada tipo de geracao ou projeto tera suas entradas no makefile. Por hora deve permitir `make proj_core`, `make prj_a4a` e `make prj_osmcodes`, cada qual disparando as suas respespectivas dependencias. <br/>(90% de qualquer forma serao *prj_a4a* disparando a conversao de shapes de vias e shapes de lotes).

Por hora apenas os "testes piloto" precisam estar 100% funcionais.

-----

Exemplos de makefile e execucao make:

```makefile
# Ingest parts of the orignal datasets into the SQL database.

orig1  = "filenameOriginal1.zip"
orig2  = "filenameOriginal2.zip"

prj_a4a: mk_line mk_point

unizip1: $(orig1)
  mkdir -p /tmp/sandbox1/
  unzip -d "/tmp/sandbox1/$(orig1)"

mk_line: unzip1
  psql_mount_csv 
...
```

* `make prj_a4a`  faz a ingestao dos dados para o projeto A4A.
* `make prj_osmcodes`  faz a ingestao dos dados para o projeto OSMcodes.

**Comment by ThierryAJean** [comment]
O makes files estão andando. Peter precisando fazer templates p entrega final para o Carlos começar a produzir.

**Comment by ThierryAJean** [comment]
CArlos fez o makefile de 16 cidades. Planeja fazer mais 4 hoje ou amanhã. Com estas 20 cidades, vamos poder gerar dados. E ver resultado.

**Comment by crebollobr** [comment]
Cidades feitas, se precisar de outras abrir nova issue
