### ISSUE TITLE
Remover optim.origin_content_type 

### ISSUE THREAD

**Issue by ppKrauss** [AddressForAll/WS#23]
Ver [optim.origin_content_type](https://github.com/AddressForAll/WS/blob/master/src/optim-step1-ini.sql#L101), e conferir se tudo migrou para  feature_type, https://github.com/AddressForAll/WS/blob/master/src/ingest-step1-ini.sql#L177

**Comment by 0e1** [comment]
Pelo que vi, tudo migrou para [ingest.feature_type](https://github.com/digital-guard/preserv/blob/main/src/ingest-step1-ini.sql#L171). Fiquei em dúvida apenas referente à https://github.com/AddressForAll/WS/blob/master/src/optim-step1-ini.sql#L114.

**Comment by 0e1** [comment]
Muito tempo já passou. Aparentemente, tudo migrado.
