### ISSUE TITLE
Resolver definitivamente o problema das permissões

### ISSUE THREAD

**Issue by ppKrauss** [AddressForAll/WS#25]
Preparar makefile. Por exemplo para resolver permissões na pasta `$(gits)`, como *sudor* rodar make com algo 

```sh
chown -R postgres:www-data /opt/gits/
find  /opt/gits/* -type d -exec chmod 774 {} \+
find  /opt/gits/* -type f -exec chmod 664 {} \+
```

Idem  `/tmp/pg_io/`, etc.

**Comment by 0e1** [comment]
`make ini_basics` executa os targets `dir_refresh` e `ini_tmprefresh` que fazem isso: https://github.com/AddressForAll/WS/blob/master/src/makefile#L43.

No preserv foi criado o target `fix_permissions` no commit https://github.com/digital-guard/preserv/commit/7e3e1f9eb2698f023f6d7c6b809ccf3e393926ec para a issue https://github.com/digital-guard/preserv/issues/24.

**Comment by crebollobr** [comment]
fechar issue. se precisar, por favor reabir
