### ISSUE TITLE
make ini_all não criou schema ingest

### ISSUE THREAD

**Issue by crebollobr** [AddressForAll/WS#27]
ingest2=# \dn
   List of schemas
   Name   |  Owner   
----------+----------
 public   | postgres
 tmp_orig | postgres
(2 rows)

**Comment by ppKrauss** [comment]
https://github.com/AddressForAll/WS/blob/master/src/ingest-step1-ini.sql
Hoje migrando .. e vai até amanhá, desculpe não ter avisado.

**Comment by 0e1** [comment]
Agora, para ter o schema ingest, usar make ini_all em `preserv/src`.
