### ISSUE TITLE
atualizar api.redirects

### ISSUE THREAD

**Issue by ppKrauss** [AddressForAll/WS#28]
ver  https://github.com/AddressForAll/WS/commit/161c0fee47bdc93700e430d8e63c40945085bb7a e planilha wget já atualizada

```
ERROR:  cannot drop table optim.redirects because other objects depend on it
DETAIL:  view api.redirects depends on table optim.redirects
HINT:  Use DROP ... CASCADE to drop the dependent objects too.
```

**Comment by 0e1** [comment]
A tabela `redirects` está agora no `schema download` e na base _dl02s_main_.
É reponsabilidade do preserv agora: https://github.com/digital-guard/preserv/blob/main/src/makefile#L225

Para atualizar a tabela, @crebollobr :
`make redirects_update pg_io=dl02s_main`

Importante notar que para a atualização da `redirects` funcionar, a folha _csv_ de [de-para](https://docs.google.com/spreadsheets/d/1CL6f0I9DSpqKxKC7QNJGCfyabq7mDOVab5QBGV5VLOk/edit#gid=0) não deve possuir repetições na coluna `de_sha256`.

**Comment by ppKrauss** [comment]
@crebollobr  seguir as [instruções acima](https://github.com/AddressForAll/WS/issues/28#issuecomment-1004942612).
(também  verificar conosco nos próximos dias a evolução do make_conf e seus makes, que sofreram modificações).

IMPORTANTE notar que 

1. **mudou** para o [projeto *preserv*](https://github.com/digital-guard/preserv)
2. precisa **adicionar mais dados** [na planilha](https://docs.google.com/spreadsheets/d/1CL6f0I9DSpqKxKC7QNJGCfyabq7mDOVab5QBGV5VLOk/edit#gid=0)
