### ISSUE TITLE
Especificação das funções SQL de API

### ISSUE THREAD

**Issue by ppKrauss** [AddressForAll/WS#32]
Depois de avançar na discussão, https://github.com/AddressForAll/specifications/discussions/9

1. Revisar o [README.md](https://github.com/AddressForAll/WS/blob/master/README.md)  para que passe a ser conteúdo de /docs 
2. Criar em [/docs/address-endpoints.md](https://github.com/AddressForAll/WS/blob/master/docs/address-endpoints.md)  o rascunho da especificação.
3. Criar exemplos de caso aderentes à proposta para testar as especificações
4. Fechar a primeira versão.

**Comment by 0e1** [comment]
Levei o conteúdo dessa issue para https://github.com/AddressForAll/WS/issues/11#issuecomment-1772641557.
