### ISSUE TITLE
autovacuum usando 100% da CPU

### ISSUE THREAD

**Issue by 0e1** [AddressForAll/WS#34]
O _autovacuum_ do postgres está usando a cpu do servidor por completo.

![Captura de tela de 2023-01-12 13-21-18](https://user-images.githubusercontent.com/41844788/212123123-e16b52b9-858f-470e-a3b1-20205cbc5583.png)

**Comment by crebollobr** [comment]
O processo já terminou.
Vendo a documentação:
https://www.postgresql.org/docs/current/routine-vacuuming.html

The autovacuum daemon, if enabled, will automatically issue ANALYZE commands whenever the content of a table has changed sufficiently. However, administrators might prefer to rely on manually-scheduled ANALYZE operations, particularly if it is known that update activity on a table will not affect the statistics of “interesting” columns. The daemon schedules ANALYZE strictly as a function of the number of rows inserted or updated; it has no knowledge of whether that will lead to meaningful statistical changes.

Se esse processo automático degradar e atrapalhar os serviços do servidor, podemos verificar a solução de fazer o vacum manual de madrugada se for o caso.
