### ISSUE TITLE
Decidir se docs.* devem redirecionar para wiki.addressforall.org

### ISSUE THREAD

**Issue by 0e1** [AddressForAll/WS#35]
Decidir se 

- https://docs.itgs.org.br
- https://docs.osm.codes
- https://docs.addressforall.org
- https://docs.digital-guard.org

Devem ser redirecionados para https://wiki.addressforall.org.

**Comment by ppKrauss** [comment]
Podemos **desativar o docs**. A ideia era boa, mas infelizmente a participação de redatores em Git é muito menor do que a participação em Wiki. 

PS: assim que o multi-idioma e os titulos se estabilizarem na Wiki, podemos criar "links mais persistentes" para os títulos da Wiki.

**Comment by 0e1** [comment]
Redirecionei docs.* para a respectiva página na wiki. Removi as pastas docs.* do servidor (backup estão no zipão).

Necessário entender o motivo de https://docs.addressforall.org/ **não** redirecionar. http://docs.addressforall.org/ redireciona.

**Comment by 0e1** [comment]
> Necessário entender o motivo de https://docs.addressforall.org/ **não** redirecionar. http://docs.addressforall.org/ redireciona.

Ambos estão redirecionando. Com isso removi do servidor a pasta docs.addressforall.org (backup no zipão).

**Comment by ppKrauss** [comment]
... *Standby* do subdomínio **docs**: precisamos decidir se a Wiki será ou não privativa, é um subconjunto de artigos da Wiki será publicado abertamente.
