### ISSUE TITLE
Subdominios e certificado Let's Encrypt

### ISSUE THREAD

**Issue by 0e1** [AddressForAll/WS#36]
@ppKrauss 

Configurar os subdomínios no serviço de hospedagem:

- [digital-guard.org](http://digital-guard.org)
- [docs.afa.codes](http://docs.afa.codes)
- [git-raw.afa.codes](http://git-raw.afa.codes)
- `git-site.afa.codes` testar com  [git-site.afa.codes/Sfc4q](http://git-site.afa.codes/Sfc4q/)
- [olc.afa.codes](http://olc.afa.codes)

@crebollobr 

- Adicionar os subdomínios anteriores ao certificado Let's Encrypt;
- Adicionar versões `www.*` para todos os domínios e subdomínios que constam atualmente no certificado.

Atualmente no certificado constam:

![screen01](https://github.com/AddressForAll/WS/assets/41844788/cfd87007-6330-4a31-82a3-4641b3399982)

**Comment by ppKrauss** [comment]
@crebollobr , dominios e subdominios ok, pode rodar o  certbot

**Comment by crebollobr** [comment]
Para o certificado ser criado o dns tem que apontar para nosso servidor
