### ISSUE TITLE
Content-Security-Policy atuais impedem funcionamento de viz.addressforall.org

### ISSUE THREAD

**Issue by 0e1** [AddressForAll/WS#38]
As configurações atuais, que conforme https://github.com/AddressForAll/WS/issues/37 não estão atualizadas nos repositórios,

```nginx
#Segurança - https://observatory.mozilla.org/analyze/viz.addressforall.org
add_header Content-Security-Policy "default-src 'self'; script-src 'report-sample' 'self'; style-src 'report-sample' 'self'; object-src 'none'; base-uri 'self'; connect-src 'self'; font-src 'self'; frame-src 'self'; img-src 'self'; manifest-src 'self'; media-src 'self'; worker-src 'none'" always;
add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
add_header X-Content-Type-Options nosniff always;
add_header X-Frame-Options "SAMEORIGIN" always;
add_header X-XSS-Protection "1; mode=block" always;
```

estão impedindo o funcionamento dos links disponíveis em https://addressforall.org/visualization.

Por exemplo: https://addressforall.org/viz/br-sp-jundiai_pk0025.01_building.html

![screen](https://github.com/AddressForAll/WS/assets/41844788/b216ff36-4cbd-4123-abe4-35e0532665d6)

**Comment by crebollobr** [comment]
Foi atualizado as politicas, por favor testar

**Comment by 0e1** [comment]
Ainda impede de obter https://addressforall.org/viz/main.js

![screen01](https://github.com/AddressForAll/WS/assets/41844788/d358cbae-eb4f-46db-9351-db65a194e381)

**Comment by crebollobr** [comment]
Qual click que você fez para essa ação? qual url?

**Comment by 0e1** [comment]
Ainda não estava funcionado essa https://addressforall.org/viz/br-sp-jundiai_pk0025.01_building.html

Gerei novamente a página. Agora está funcionado.

**Comment by crebollobr** [comment]
Pode ser algo do browser, estou testando com o Edge, firefox e chrome

**Comment by crebollobr** [comment]
a noite vou testar no Linux

**Comment by 0e1** [comment]
Testei. Tudo funcioando. Muito obrigado.
