### ISSUE TITLE
Vincular IDs de geometrias com IDs de planilha

### ISSUE THREAD

**Issue by IgorEliezer** [AddressForAll/WS#6]
## Grupo L1, L2 e L3: `lote id`

Municípios que possuem o mapa de lotes sem endereços, mas com um número de identificação (ID, número de cadastro imobiliário, setor/quadra/lote etc).

### O que precisa fazer
1. Pedir às prefeituras o fornecimento de uma planilha que relacione o número de identificação com o endereço.
2. Vincular, pelo ID, os respectivos endereços constantes na planilha nas geometrias dos lotes.
3. _**(Etapa futura):** gerar ponto de endereço na testada do lote._

### Municípios
Grupo L1: lotes com ID e há planilha:
- [ ] SP - São Paulo

Grupo L2: lotes com número mas a planilha precisa ser fornecida:
- PR - Curitiba/IPPUC
- PE - Refice

Grupo L3: lotes com ID mas a planilha precisa ser fornecida:
- ES - Serra
- ES - Vila Velha
- RJ - Niterói
- SP - Jundiaí
- SP - Laranjal Paulista _(caso especial: os lotes possuem ID mas a ID está numa camada separada)_

**Comment by IgorEliezer** [comment]
Completei a lista dos municípios.

**Comment by IgorEliezer** [comment]
SP-Itu sai daqui para https://github.com/AddressForAll/WS/issues/8

**Comment by ppKrauss** [comment]
Oops, ainda não sei qual o melhor local dessa *issue*... Critérios:

* para ser do [projeto digital-preservartion-BR](https://github.com/AddressForAll/digital-preservartion-BR/issues) precisa ser tratamento ainda bruto ou uso no PostGIS para testes de qualidade e volumetria, não para ingestão final do AddressForAll.

* para ser do [projeto AddressForAll](https://github.com/AddressForAll/prj-AddressForAll/issues) precisa ser ingestão de dados úteis e modelados para o endereço, não pode ser "outros dados".

* para ser aqui do WS, é só questão de web-service e acertos das APIs para mostrar os dados já ingeridos em algum lugar, ou os metadados de serviços tais como a Eclusa.

Acho que essa issue aqui deveria ir pro *prj-AddressForAll*.

**Comment by 0e1** [comment]
Essa issue antiga perdeu o objeto, me parece. Se existir motivo para não fechá-la, reabri-la.
