### ISSUE TITLE
Atribuir nome de rua em pontos de numeração predial ou ID

### ISSUE THREAD

**Issue by IgorEliezer** [AddressForAll/WS#7]
## Grupo P2, P3 e PL2: `ponto numero|id`

Municípios que possuem o mapa de pontos de endereços, mas o ponto contém somente o número predial ou um ID.

### O que precisa fazer
* Atribuir os respectivos nomes de logradouro nestes pontos de endereços.
* Requer:
  * planilha ou outra fonte de dados para cruzar; ou
  * eixos de vias com nome.

### Municípios
Grupo P2: pontos com ID:
- SP - Santos
- RS - Porto Alegre

Grupo P3: pontos com número predial:
- SP - São Vicente (2 planilhas CSV de pontos)

Grupo PL2: pontos com número predial e lotes com ID:
- PR - São José dos Pinhais

### Notas
1. Precisa decidir se precisa planilha ou se vai obter o nome dos eixos de logradouro.
2. Grupos P2 e P3: nos casos acima, não foram fornecidos eixos de vias

**Comment by IgorEliezer** [comment]
Completei a lista dos municípios.

**Comment by 0e1** [comment]
Me parece que o teor da issue já foi atendido pelo esquema layer/cadlayer.
Fecharei a issue.
