### ISSUE TITLE
Gerar ponto de endereço na testada de lote

### ISSUE THREAD

**Issue by IgorEliezer** [AddressForAll/WS#8]
## Grupo L1: `lote endereco`

Municípios que possuem o mapa de lotes com endereços.

### O que precisa fazer
* Gerar ponto de endereço (rua, número) na testada de lote.

### Municípios
- [ ] PR - Cascavel
- [ ] SP - Itu
- [ ] PR - Pinhais
- [ ] SP - Sorocaba
- [ ] ES - Vitória

**Comment by ppKrauss** [comment]
Oops, ainda não sei qual o melhor local dessa *issue*... Critérios:

* para ser do [projeto digital-preservartion-BR](https://github.com/AddressForAll/digital-preservartion-BR/issues) precisa ser tratamento ainda bruto ou uso no PostGIS para testes de qualidade e volumetria, não para ingestão final do AddressForAll.

* para ser do [projeto AddressForAll](https://github.com/AddressForAll/prj-AddressForAll/issues) precisa ser ingestão de dados úteis e modelados para o endereço, não pode ser "outros dados".

* para ser aqui do WS, é só questão de web-service e acertos das APIs para mostrar os dados já ingeridos em algum lugar, ou os metadados de serviços tais como a Eclusa.

Acho que essa issue aqui deveria ir pro *prj-AddressForAll*.

**Comment by ppKrauss** [comment]
Ficou resolvido conforme tabela `ingest.feature_type` que a ingestão desses casos será feita por *ftype parcel*, ver [ilustração](https://github.com/digital-guard/preserv/blob/main/docs/assets-src.md)

**Comment by 0e1** [comment]
Essa issue antiga perdeu o objeto, me parece. Se existir motivo para não fechá-la, reabri-la.
