### ISSUE TITLE
Documentando e fechando API, primeira parte

### ISSUE THREAD

**Issue by ppKrauss** [AddressForAll/WS#9]
Desenvolvedores envolvidos no projeto devem executar passo-a-passo as instalações, estabelecer consenso sobre a melhor sequencia do passo-a-passo, e documentar.

As [decisões de projeto na infraestrutura AddressForAll](https://github.com/AddressForAll/specifications/blob/master/docs/spec02-workflow.md) em 2020 incluem:

* uso do PostgreSQL v12 (+PostGIS etc.) em ambiente UBUNTU 20 LTS, direto (sem dockagem).
* uso do [PostgREST v7.0](http://postgrest.org/en/v7.0.0), **dockado** e conectado ao PostgreSQL principal (não-dockado).
* na interface final os javascripts conforme demanda da página:
   - https://d3js.org/ (só quando demandar)
   -  http://tabulator.info/  (sem jQuery) (só quando demandar visualização tabular dos dados da API)
   - https://vega.github.io/vega-lite/ (só quando demandar gráficos analíticos) 
   - https://leafletjs.com/ (só quando demandar mapas)
   - (evitando e usando apenas quando D3js não der conta)   https://jquery.com

**Comment by 0e1** [comment]
Informações sobre infraestrutura agora estão em https://wiki.addressforall.org/doc/Documenta%C3%A7%C3%A3o_da_infraestrutura, não vejo mais motivos para essa issue continuar aberta.
